plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.google.gms.google.services)
}

android {
    namespace 'com.umainebiomechanicslab.biomechanicslabapp'
    compileSdk 34

    defaultConfig {
        applicationId "com.umainebiomechanicslab.biomechanicslabapp"
        minSdk 31
        targetSdk 35
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    buildToolsVersion '34.0.0'
}

dependencies {

    implementation libs.appcompat
    implementation libs.material
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core

    implementation libs.constraintlayout
    implementation libs.okhttp
    implementation libs.firebase.database
    implementation libs.firebase.storage
    implementation libs.firebase.auth
    implementation libs.play.services.auth
    implementation libs.firebase.appcheck.playintegrity

    def movellaFilesDir = file("$projectDir/../MOVELLAFiles")
    implementation fileTree(dir: movellaFilesDir, include: ['*.aar', '*.jar'], exclude: [])

}